export const errorCodes = {

    SUCCESS: 'SUCCESS',
    REQUIRED_PARAMETER_MISSING: 'REQUIRED_PARAMETER_MISSING',
    UNKNOWN_SERVER_ERROR: 'UNKNOWN_SERVER_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',

    EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    EMAIL_NOT_PROVIDED: 'EMAIL_NOT_PROVIDED',
    PASSWORD_NOT_PROVIDED: 'PASSWORD_NOT_PROVIDED',
    OTP_NOT_PROVIDED: 'OTP_NOT_PROVIDED',
    ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
    ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
    
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
    INVALID_FIRST_NAME: 'INVALID_FIRST_NAME',
    INVALID_LAST_NAME: 'INVALID_LAST_NAME',
    INVALID_USER_ID: 'INVALID_USER_ID',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    INVALID_OTP: 'INVALID_OTP',

    USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
    USER_NOT_EXIST: 'USER_NOT_EXIST',
    USER_SUSPENDED: 'USER_SUSPENDED',
    ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
    EMAIL_ALREADY_TAKEN: 'EMAIL_ALREADY_TAKEN',

    FILE_SIZE_LIMIT_EXCEED: 'FILE_SIZE_LIMIT_EXCEED',

    LIMIT_EXCEED_TRY_IN_24HR: 'LIMIT_EXCEED_TRY_IN_24HR',
    LIMIT_EXCEED_TRY_IN_60MIN: 'LIMIT_EXCEED_TRY_IN_60MIN',
    LIMIT_EXCEED_TRY_IN_5MIN: 'LIMIT_EXCEED_TRY_IN_5MIN',

}